<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Pricing.Import.Contracts/Pricing.Import.Contracts.csproj" />
    <ProjectReference Include="../Pricing.Import.Infrastructure/Pricing.Import.Infrastructure.csproj" />
  </ItemGroup>

</Project>
